apiVersion: v1
kind: PersistentVolume
metadata:
  name: bestrong-hostpath-pv
spec:
  capacity:
    storage: {{ .Values.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: {{ .Values.hostPath }}
