apiVersion: v1
kind: PersistentVolume
metadata:
  name: bestrong-shared-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }} 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: {{ .Values.persistence.hostPath.path }}
    type: DirectoryOrCreate
