apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bestrong-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: {{ .Values.size }}