apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opencost-cert
  namespace: opencost
spec:
  dnsNames:
    - opencost.bestrong.pp.ua
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: opencost-tls
