apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bestrong-tls
  namespace: default
spec:
  dnsNames:
    - bestrong.pp.ua
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod  
  secretName: bestrong-tls
